### ISSUE TITLE
problem with model S2VTModel

### ISSUE THREAD

**Issue by qy-feng** [xiadingZ/video-caption-pytorch#13]
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`
This error occurs when I use S2VTModel, but everything works well with S2VTAttModel. As I started with S2VTModel and want to fix this bug, but failed. Do you have any idea?

**Comment by ParitoshParmar** [comment]
@qy-feng , try commenting out lines 51, 52 (`self.rnn1.flatten_parameters()`;
`self.rnn2.flatten_parameters()`) in S2VTModel. It should resolve your issue.

**Comment by qy-feng** [comment]
Perfectly solved. Thanks!
