### ISSUE TITLE
ValueError: could not convert string to float: 'Error: specify Meteor stats'

### ISSUE THREAD

**Issue by ivy94419** [xiadingZ/video-caption-pytorch#15]
I used Python3.5 and Pytorch0.4 in ubuntu, I got this errors:

```
init COCO-EVAL scorer
Traceback (most recent call last):
  File "eval.py", line 122, in <module>
    main(opt)
  File "eval.py", line 91, in main
    test(model, crit, dataset, dataset.get_vocab(), opt)
  File "eval.py", line 57, in test
    valid_score = scorer.score(gts, samples, samples.keys())
  File "/host/xxx/video_caption/video_caption_pytorch/misc/cocoeval.py", line 88, in score
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
    score = float(self.meteor_p.stdout.readline().decode().strip())
ValueError: could not convert string to float: 'Error: specify Meteor stats'
```
How to deal with it?

**Comment by zhjohnchan** [comment]
I has faced the same problem as you. I found the data loader was empty when running `eval.py` because it was empty in `[test]` of my `info.json`. My steps to solve this problem are as follows:
1. Download the `three json files` from baiduyun.
2. Rerun `prepro_vocab.py`.
3. Retrain model.

**Comment by ivy94419** [comment]
@zhjohnchan Thank you！

**Comment by DogeFlow** [comment]
@zhjohnchan   Hello, I encountered the same error, but now only two json files can be downloaded. What is the third json file?
