### ISSUE TITLE
Compiling PyTorch from source

### ISSUE THREAD

**Issue by Blues5** [xiadingZ/video-caption-pytorch#3]
I guess, providing these steps in the READme might help new users-

run the Anaconda installation, let Anaconda modify your .bashrc file
source .bashrc
module load apps cuda/8.0
to check if cuda is installed properly - ls /usr/local/cuda-8.0/lib64
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]
conda install numpy pyyaml mkl setuptools cmake cffi
conda install -c soumith magma-cuda80
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch/
CUDA_HOME="/usr/local/cuda-8.0" python setup.py install
--

**Comment by xiadingZ** [comment]
I think how to compile pytorch from cuda should be placed in issues of pytorch project
