### ISSUE TITLE
A bug: TypeError: gru() received an invalid combination of arguments - got (Tensor, Tensor, list, bool, int, float, bool, int, bool), but expected one of: 

### ISSUE THREAD

**Issue by tuyunbin** [xiadingZ/video-caption-pytorch#32]
**Problem**
My python version is 2.7(but this bug also exist when using python3+), and pytorch version is 1.1.0
TypeError: gru() received an invalid combination of arguments - got (Tensor, Tensor, list, bool, int, float, bool, int, bool), but expected one of:
(Tensor data, Tensor batch_sizes, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list!, !bool!, !int!, !float!, !bool!, !int!, bool)
(Tensor input, Tensor hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
didn't match because some of the arguments have invalid types: (Tensor, Tensor, !list!, bool, int, float, bool, !int!, bool)
**Solution:**
change bidirectional=opt["bidirectional"] to bidirectional=bool(opt["bidirectional"])

**Comment by piperino11** [comment]
Solution:
change bidirectional=opt["bidirectional"] to bidirectional=bool(opt["bidirectional"])
in which file?

**Comment by zl535320706** [comment]
> Solution:
> change bidirectional=opt["bidirectional"] to bidirectional=bool(opt["bidirectional"])
> in which file?

not in a file , in def __init__, define your self.rnn(...bidirectional=bool(bidirectional))
