### ISSUE TITLE
As there are issues with FFmpeg compilation for yasm updation, using opencv sounds reasonable. The following block needs to be modified and incorporated.

### ISSUE THREAD

**Issue by Blues5** [xiadingZ/video-caption-pytorch#4]
import sys
import argparse
import cv2
print(cv2.__version__)
def extractImages(pathIn, pathOut):
    vidcap = cv2.VideoCapture(pathIn)
    success,image = vidcap.read()
    count = 0
    success = True
    while success:
      success,image = vidcap.read()
      print ('Read a new frame: ', success)
      cv2.imwrite( pathOut + "\\frame%d.jpg" % count, image)     # save frame as JPEG file
      count += 1

if __name__=="__main__":
    print("aba")
    i = argparse.ArgumentParser()
    i.add_argument("--pathIn", help="path to video")
    i.add_argument("--pathOut", help="path to images")
    args = i.parse_args()
    print(args)
    extractImages(args.pathIn, args.pathOut)

**Comment by xiadingZ** [comment]
you can install ffmpeg using conda, independent of os version
