### ISSUE TITLE
error in eval.py : BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by fikarchamiiiim** [xiadingZ/video-caption-pytorch#44]
vocab size is  183
number of train videos:  8
number of val videos:  1
number of test videos:  1
['data/feats/resnet152/data/train-video']
load feats from ['data/feats/resnet152/data/train-video']
max sequence length in data is 28
/home/chamim/SkripsiP3/lib/python3.6/site-packages/torch/nn/modules/rnn.py:51: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/home/chamim/SkripsiP3/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
init COCO-EVAL scorer
eval.py:34: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  json.load(open(opt["input_json"]))['sentences'])
/home/chamim/SkripsiP3/lib/python3.6/site-packages/torch/nn/functional.py:1339: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "eval.py", line 122, in <module>
    main(opt)
  File "eval.py", line 91, in main
    test(model, crit, dataset, dataset.get_vocab(), opt)
  File "eval.py", line 57, in test
    valid_score = scorer.score(gts, samples, samples.keys())
  File "/home/chamim/SkripsiP3/skripsi/video captioning/misc/cocoeval.py", line 88, in score
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 41, in compute_score
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

please help me :( when I did an evaluation with eval.py, an error occurred BrokenPipeError: [Errno 32] Broken pipe, is there anything I need to fix? thank you

**Comment by HaiyiMei** [comment]
Maybe this issue will help you :) [url](https://github.com/tylin/coco-caption/issues/17)

**Comment by fikarchamiiiim** [comment]
Thankyou @HaiyiMei

**Comment by Sciroccogti** [comment]
I ran into this error as well, and I fixed it by directly running the java command in the `meteor.py`:
```
java -jar -Xms2G path/to/meteor-1.5.jar -stdio -l en -norm
```
And it told me that the `paraphrase-en.gz` is not found, so copy the file to the `data` dir fixed my error.

I hope this can help someone.
