### ISSUE TITLE
c3d feats extraction example

### ISSUE THREAD

**Issue by dmandreev** [xiadingZ/video-caption-pytorch#8]
Hello! Thank you for your work! Is c3d features currently not supported? I saw some traces in sources, but not sure. Could you please give any hints? Is these features have to be extracted as resnet features and later simply jointed?

**Comment by xiadingZ** [comment]
It supports. you can use [video-classification-3d-cnn-pytorch](https://github.com/kenshohara/video-classification-3d-cnn-pytorch) to extract c3d features, then mean pool to get 2048 dim feature for each video

**Comment by HimaVarsha94** [comment]
Where is the preprocess file?

**Comment by Sciroccogti** [comment]
Hi! I do used the repo [video-classification-3d-cnn-pytorch](https://github.com/kenshohara/video-classification-3d-cnn-pytorch), but its output is a json. How can I use that with your codes?

Thank you for your work!

**Comment by Sciroccogti** [comment]
I used this to turn the json into npy:

```Python
import json
import numpy as np
import os

videos = json.load(open('./output.json', 'r'))

if not os.path.exists("data/3dfeature/"):
    os.makedirs("data/3dfeature/")

for video in videos:
    name = str(video["video"].split(".")[0])
    segments = video["clips"]
    feat = []
    for segment in segments:
        feat += segment["features"]
    np.save("data/3dfeature/" + name + ".npy", feat)

```
